exception UnknownVariable of string
exception NotAnId
exception FloatOpNotSupported
exception NotALiteral
exception UninitializedArray of string
exception IllegalAssignment
exception NotAnArray
exception NotADatatype
exception NotAssignable
